server.port: 9090

spring:
  cloud.gateway.routes:
  - id: bar-service
    uri: http://${app.bar-service.host}:${app.bar-service.port}/
    predicates:
      - Path=/bars/**
  boot.admin.client:
    url: http://${app.admin-server.host}:${app.admin-server.port}
    username: admin
    password: admin
  zipkin.base-url: http://${app.zipkin.host}:${app.zipkin.port}/
  sleuth.sampler.probability: 1

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

app:
  admin-server:
    host: localhost
    port: 8080
  zipkin: 
    host: localhost
    port: 9411
  bar-service:
    host: localhost
    port: 9091

---
spring.profiles: docker

app:
  admin-server.host: admin-server
  bar-service.host: bar-service
  zipkin.host: zipkin