server.port: 9090

spring:
  boot.admin.client:
    url: http://${app.admin-server.host}:${app.admin-server.port}
    username: admin
    password: admin
  zipkin.base-url: http://${app.zipkin.host}:${app.zipkin.port}/
  sleuth.sampler.probability: 1

  cloud.gateway.routes:
  - id: bar-composite
    uri: lb://bar-composite
    predicates:
      - Path=/bars/**
  - id: trip-service
    uri: lb://trip-service
    predicates:
      - Path=/trips/**

eureka.client.serviceUrl.defaultZone: http://${app.eureka.host}:${app.eureka.port}/eureka
management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

app:
  admin-server:
    host: localhost
    port: 8080
  eureka:
    host: localhost
    port: 8761
  zipkin: 
    port: 9411
    host: localhost

---
spring.profiles: docker

app:
  admin-server.host: admin-server
  eureka.host: discovery
  zipkin.host: zipkin