server.port: 9093

spring:
  boot.admin.client:
    url: http://${app.admin-server.host}:${app.admin-server.port}
    username: admin
    password: admin
  zipkin.base-url: http://${app.zipkin.host}:${app.zipkin.port}/
  sleuth.sampler.probability: 1
  security.oauth2.resourceserver.jwt.issuer-uri: http://${app.keycloak.host}:${app.keycloak.port}/auth/realms/hhf

eureka.client.serviceUrl.defaultZone: http://${app.eureka.host}:${app.eureka.port}/eureka
management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

springdoc:
  packagesToScan: com.mathieuaime.hhf.composite.bar
  api-docs.path: /bars/v3/api-docs

app:
  admin-server:
    host: localhost
    port: 8080
  eureka:
    host: localhost
    port: 8761
  keycloak:
    host: localhost
    port: 8090
  zipkin:
    host: localhost
    port: 9411

---
spring.profiles: docker
server.port: 8080

app:
  admin-server.host: admin-server
  eureka.host: discovery
  keycloak:
    host: keycloak
    port: 8080
  zipkin.host: zipkin