server.port: 9094

spring:
  boot.admin.client:
    url: http://${app.admin-server.host}:${app.admin-server.port}
    username: admin
    password: admin
  zipkin.base-url: http://${app.zipkin.host}:${app.zipkin.port}/
  sleuth.sampler.probability: 1
management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

app:
  admin-server:
    host: localhost
    port: 8080
  zipkin: 
    host: localhost
    port: 9411

---
spring.profiles: docker
server.port: 8080

app:
  admin-server.host: admin-server
  zipkin.host: zipkin